/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compras.vista;


import compras.vista.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import logistica.controlador.clsProductos;
import logistica.modelo.daoProductos;
import compras.modelo.daoProveedores;
import compras.controlador.clsProveedores;
import compras.controlador.clsCompras;
import compras.modelo.daoCompras;
import compras.modelo.daoCotizacionCompras;
import compras.controlador.clsCotizacionCompras;





/**
 *
 * @author visitante
 */
public class frmMantenimientoCotizacionCompras extends javax.swing.JInternalFrame {

    public void ComboCliente() {
        daoProveedores cotiDAO = new daoProveedores();
        List<clsProveedores> cotizacion = cotiDAO.select();
        cbox_clicodigo.addItem("Seleccione un proveedor");
        //cbox_clicodigo.removeAllItems();
        for (int i = 0; i < cotizacion.size(); i++) {
            cbox_clicodigo.addItem(String.valueOf(cotizacion.get(i).getprocodigo()));
        }
    }
    
        
        public void ComboProducto() {
        daoProductos cotiDAO = new daoProductos();
        List<clsProductos> cotizacion = cotiDAO.select();
        cbox_prodcodigo.addItem("Seleccione un Producto");
        //cbox_clicodigo.removeAllItems();
        for (int i = 0; i < cotizacion.size(); i++) {
            cbox_prodcodigo.addItem(String.valueOf(cotizacion.get(i).getProdcodigo()));
        }
    }
        
    
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("No.Cotizacion");//ENCABEZADO
        modelo.addColumn("ID proveedor");
        modelo.addColumn("Fecha");
        modelo.addColumn("ID Producto");//DETALLE
        modelo.addColumn("Cantidad");
        modelo.addColumn("Total");
        

        daoCotizacionCompras cotiDAO = new daoCotizacionCompras();
        List<clsCotizacionCompras> cotizacion = cotiDAO.select();
        
        daoCotizacionCompras cotiDAO2 = new daoCotizacionCompras();
        List<clsCotizacionCompras> cotizacion2 = cotiDAO2.select2();
        
        tablaCompras.setModel(modelo);
        String[] dato = new String[10];
        for (int i = 0; i < cotizacion.size(); i++) {
            dato[0] = cotizacion.get(i).getCce_documento();//ENCABEZADO
            dato[1] = Integer.toString(cotizacion.get(i).getProcodigo());
            dato[2] = cotizacion.get(i).getCce_fecha();
            
            dato[3] = Integer.toString(cotizacion2.get(i).getProdcodigo());//DETALLE
            dato[4] = Integer.toString(cotizacion2.get(i).getCce_cantidad_producto());
            dato[5] = Integer.toString(cotizacion2.get(i).getCce_total_producto());
            

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscarCotizacion() {
        clsCotizacionCompras comprasAConsultar = new clsCotizacionCompras();
        clsCotizacionCompras comprasAConsultar2 = new clsCotizacionCompras();
        daoCotizacionCompras cotiDAO = new daoCotizacionCompras();   
        daoCotizacionCompras cotiDAO2 = new daoCotizacionCompras();
        
        //***************************ENCABEZADO*********************************
        comprasAConsultar.setCce_documento(txtbuscado.getText());
        comprasAConsultar = cotiDAO.query(comprasAConsultar); 
        txtIDDocumento.setText(comprasAConsultar.getCce_documento());         
        cbox_clicodigo.setSelectedItem(Integer.toString(comprasAConsultar.getProcodigo()));
        txtFecha.setText(comprasAConsultar.getCce_fecha());
        //***************************DETALLE***********************************
        comprasAConsultar2.setCce_documento(txtbuscado.getText());
        comprasAConsultar2 = cotiDAO2.query2(comprasAConsultar2); 
        txtIDDocumento.setText(comprasAConsultar2.getCce_documento()); 
        cbox_prodcodigo.setSelectedItem(Integer.toString(comprasAConsultar2.getProdcodigo()));
        txtCantidad.setText(Integer.toString(comprasAConsultar2.getCce_cantidad_producto()));
        txtTotal.setText(Integer.toString(comprasAConsultar2.getCce_total_producto()));

        txtIDDocumento.setEnabled(false);
        
    }

    public frmMantenimientoCotizacionCompras() {
        initComponents();
        llenadoDeTablas();
        ComboCliente();
        ComboProducto();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        txtbuscado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        label5 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        label11 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        label14 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        cbox_clicodigo = new javax.swing.JComboBox<>();
        cbox_prodcodigo = new javax.swing.JComboBox<>();
        label8 = new javax.swing.JLabel();
        txtIDDocumento = new javax.swing.JTextField();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cotizacion de Compras");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 95, -1));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 95, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 95, -1));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label1.setText("Cotización ");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 0, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 95, -1));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Proveedor codigo");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 102, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 95, -1));

        txtFecha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 263, -1));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Fecha");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, -1, -1));

        lb.setForeground(new java.awt.Color(204, 204, 204));
        lb.setText(".");
        getContentPane().add(lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 20, 13, -1));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, -1));

        tablaCompras.setBackground(new java.awt.Color(51, 255, 255));
        tablaCompras.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaCompras);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 850, 450));

        label11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label11.setText("Codigo Producto");
        getContentPane().add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        label12.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label12.setText("Total Producto");
        getContentPane().add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        label14.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label14.setText("Cantidad Producto");
        getContentPane().add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 263, -1));

        txtTotal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 263, -1));

        cbox_clicodigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_clicodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_clicodigoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_clicodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 260, -1));

        cbox_prodcodigo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_prodcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_prodcodigoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_prodcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 263, -1));

        label8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label8.setText("No.Cotizacion");
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 57, -1, -1));

        txtIDDocumento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtIDDocumento.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtIDDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 263, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        //****************DETALLE****************
        daoCotizacionCompras cotiDAO2 = new daoCotizacionCompras();
        clsCotizacionCompras comprasAEliminar2 = new clsCotizacionCompras();
        comprasAEliminar2.setCce_documento(txtbuscado.getText());
        cotiDAO2.delete2(comprasAEliminar2);
        //****************ENCABEZADO****************
        daoCotizacionCompras cotiDAO = new daoCotizacionCompras();
        clsCotizacionCompras comprasAEliminar = new clsCotizacionCompras();
        comprasAEliminar.setCce_documento(txtbuscado.getText());
        cotiDAO.delete(comprasAEliminar);        
        llenadoDeTablas();
        //FUNCION PARA HABILITAR TEXTO DE ID DOCUMENTO
        txtIDDocumento.setEnabled(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        daoCotizacionCompras cotiDAO = new daoCotizacionCompras();
        daoCotizacionCompras cotiDAO2 = new daoCotizacionCompras();
        clsCotizacionCompras comprasAInsertar = new clsCotizacionCompras();
        clsCotizacionCompras comprasAInsertar2 = new clsCotizacionCompras();
        //******************ENCABEZADO**********************
        comprasAInsertar.setCce_documento(txtIDDocumento.getText());
        comprasAInsertar.setProcodigo(Integer.parseInt(cbox_clicodigo.getSelectedItem().toString()));
        comprasAInsertar.setCce_fecha(txtFecha.getText());
        //******************DETALLE**************************
        comprasAInsertar2.setCce_documento(txtIDDocumento.getText());
        comprasAInsertar2.setProdcodigo(Integer.parseInt(cbox_prodcodigo.getSelectedItem().toString()));
        comprasAInsertar2.setCce_cantidad_producto(Integer.parseInt(txtCantidad.getText()));
        comprasAInsertar2.setCce_total_producto(Integer.parseInt(txtTotal.getText()));
       
        
        cotiDAO.insert(comprasAInsertar);
        cotiDAO2.insert2(comprasAInsertar2);
        //FUNCION PARA HABILITAR TEXTO DE ID DOCUMENTO
        txtIDDocumento.setEnabled(true);
        llenadoDeTablas();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscarCotizacion();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        daoCotizacionCompras cotiDAO2 = new daoCotizacionCompras();
        clsCotizacionCompras comprasAActualizar2 = new clsCotizacionCompras();
        daoCotizacionCompras cotiDAO = new daoCotizacionCompras();
        clsCotizacionCompras comprasAActualizar = new clsCotizacionCompras();
        //******************DETALLE**************************
               
        comprasAActualizar2.setCce_documento(txtbuscado.getText());
        comprasAActualizar2.setCce_documento(txtIDDocumento.getText());
        comprasAActualizar2.setProdcodigo(Integer.parseInt(cbox_prodcodigo.getSelectedItem().toString()));
        comprasAActualizar2.setCce_cantidad_producto(Integer.parseInt(txtCantidad.getText()));
        comprasAActualizar2.setCce_total_producto(Integer.parseInt(txtTotal.getText()));

               
        cotiDAO2.update2(comprasAActualizar2);
        //******************ENCABEZADO**********************
        comprasAActualizar.setCce_documento(txtbuscado.getText());
        comprasAActualizar.setProcodigo(Integer.parseInt(cbox_clicodigo.getSelectedItem().toString()));
        comprasAActualizar.setCce_fecha(txtFecha.getText());       
        cotiDAO.update(comprasAActualizar);
        //FUNCION PARA HABILITAR TEXTO DE ID DOCUMENTO
        txtIDDocumento.setEnabled(true);
        llenadoDeTablas();     
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtIDDocumento.setText("");
        cbox_clicodigo.setSelectedIndex(0);
        txtFecha.setText("");
        
        cbox_prodcodigo.setSelectedIndex(0);
        txtCantidad.setText("");
        txtTotal.setText("");
       
        txtbuscado.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        //FUNCION PARA HABILITAR TEXTO DE ID DOCUMENTO
        txtIDDocumento.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void cbox_clicodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_clicodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_clicodigoActionPerformed

    private void cbox_prodcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_prodcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_prodcodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbox_clicodigo;
    private javax.swing.JComboBox<String> cbox_prodcodigo;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIDDocumento;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
