/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;

import seguridad.modelo.daoUsuario;
import seguridad.controlador.clsUsuario;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import seguridad.controlador.clsUsuarioConectado;
import seguridad.modelo.clsConexion;




/**
 *
 * @author visitante
 */

public class frmCambioContrasena extends javax.swing.JInternalFrame {
    private static final String SQL_UPDATE = "UPDATE tbl_usuario SET usucontrasena=? WHERE usuid =?";
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement stm = null;
    public int usuid;
    
    public frmCambioContrasena(int usunombre) {
     this.usuid=1;
     clsUsuario AConsultar = new clsUsuario();
        daoUsuario perDAO = new daoUsuario();
    }
    
    
    
    public frmCambioContrasena() {
        initComponents();
        lblUsuarioRegistrado.setText(clsUsuarioConectado.getUsunombre());
    }
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        lblUsuarioRegistrado = new javax.swing.JLabel();
        txtnueva_contrasena = new javax.swing.JPasswordField();
        txtconfi_contrasena = new javax.swing.JPasswordField();
        btnModificar = new javax.swing.JButton();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cambio contraseña");
        setVisible(true);

        label1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label1.setText("Ingrese nueva contraseña");

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Nueva contraseña");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label5.setText("Confirmar la nueva contraseña");

        txtnueva_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnueva_contrasenaActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtconfi_contrasena, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5)
                                    .addComponent(txtnueva_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label1)
                            .addComponent(lblUsuarioRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioRegistrado)
                .addGap(18, 18, 18)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnueva_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtconfi_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModificar))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
     txtnueva_contrasena.setText("");
     txtconfi_contrasena.setText("");
     
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtnueva_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnueva_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnueva_contrasenaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        PreparedStatement stmt = null;
        int rows = 0;
        clsUsuario AConsultar = new clsUsuario();
        daoUsuario perDAO = new daoUsuario();
        clsUsuarioConectado usuarioRegistrado = new clsUsuarioConectado();                
        usuarioRegistrado.setUsunombre(txtnueva_contrasena.getText().trim());
        
        if(txtnueva_contrasena.getText().equals(txtconfi_contrasena.getText())){
            try{
                String updateQuery = "UPDATE `tbl_usuario` SET `usucontrasena`=? WHERE usuid=?";
                System.out.println(updateQuery);
                con = DriverManager.getConnection("jdbc:mysql://localhost/proyectobd122022","remoto","123456");
                stmt=con.prepareStatement(updateQuery);
                stmt.setString(1, txtconfi_contrasena.getText());
              //stmt.usuarioRegistrado.setUsunombre(2,txtusuario ); CON LA CREACION DE ESTE UPDATE USE DE GUIA EL "UPDATE DE daoUsuario"
                rows = stmt.executeUpdate();
                System.out.println(stmt);
                JOptionPane.showMessageDialog(null, "Contraseña modificada");
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }        
    }//GEN-LAST:event_btnModificarActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lblUsuarioRegistrado;
    private javax.swing.JLabel lbusu;
    private javax.swing.JPasswordField txtconfi_contrasena;
    private javax.swing.JPasswordField txtnueva_contrasena;
    // End of variables declaration//GEN-END:variables

}
