/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;


import seguridad.modelo.daoPerfilAplicaciones;
import seguridad.modelo.daoAplicacion;
import seguridad.controlador.clsPerfilAplicaciones;
import seguridad.controlador.clsAplicacion;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import seguridad.controlador.clsPerfil;
import seguridad.modelo.daoPerfil;


/**
 *
 * @author visitante
 */
public class frmMantenimientoPerfilAplicaciones extends javax.swing.JInternalFrame {
    


    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Aplicacion");
        daoAplicacion aplicacionDAO = new daoAplicacion();
        List<clsAplicacion> aplicaciones = aplicacionDAO.select();
        tablaAplicaciones.setModel(modelo);
        
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            
            dato[0] = Integer.toString(aplicaciones.get(i).getId_aplicacion());
            dato[1] = aplicaciones.get(i).getNombreAplicacion();
        
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
        
    }
           
    
    public void buscarAsignacion()
    {
        clsPerfilAplicaciones AConsultar = new clsPerfilAplicaciones();
        daoPerfilAplicaciones perDAO = new daoPerfilAplicaciones();
        AConsultar.setPerid(txtperid.getText());
        DefaultTableModel modelo = new DefaultTableModel();
            
        
        modelo.addColumn("AplicacionID");
        modelo.addColumn("PerfilID");
        modelo.addColumn("NombreAPL");
        
        //daoPerfilApps aplicacion = new daoPerfilAplicaciones();
        List<clsPerfilAplicaciones> aplicaciones = perDAO.select2(AConsultar);
        tablaAsignacion.setModel(modelo);
                
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            dato[0] = aplicaciones.get(i).getAplid();
            dato[1] = aplicaciones.get(i).getPerid();
            dato[2] = aplicaciones.get(i).getAplnombre();
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    
    }
           
           

    

   

    public frmMantenimientoPerfilAplicaciones() {
        initComponents();
        llenadoDeTablas(); 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsignacion = new javax.swing.JTable();
        lbl_Aaplicacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_code = new javax.swing.JLabel();
        txtapid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtperid = new javax.swing.JTextField();
        lbl_code1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaAplicaciones = new javax.swing.JTable();
        lbl_code2 = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Perfil aplicaciones");
        setPreferredSize(new java.awt.Dimension(900, 400));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAsignacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aplicacion_ID", "PerfilI_D", "NombreAPL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaAsignacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 330, 210));

        lbl_Aaplicacion.setText("Asignacion de Aplicaciones");
        getContentPane().add(lbl_Aaplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabel2.setText("APLICACIONES:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lbl_code.setText("Codigo Perfil A insertar");
        getContentPane().add(lbl_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        txtapid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapidActionPerformed(evt);
            }
        });
        getContentPane().add(txtapid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, -1));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 80, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 80, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        txtperid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperidActionPerformed(evt);
            }
        });
        getContentPane().add(txtperid, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, -1));

        lbl_code1.setText("PERFIILES:");
        getContentPane().add(lbl_code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, -1));

        tablaAplicaciones.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaAplicaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Aplicacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaAplicaciones);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 290, 140));

        lbl_code2.setText("Codigo Aplicacion A insertar");
        getContentPane().add(lbl_code2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                               
           daoPerfilAplicaciones vendedorDAO = new daoPerfilAplicaciones();
        clsPerfilAplicaciones vendedorAInsertar = new clsPerfilAplicaciones();
        vendedorAInsertar.setPerid(txtperid.getText());
         vendedorAInsertar.setAplid(txtapid.getText());
        vendedorDAO.insert(vendedorAInsertar);
        llenadoDeTablas();
   
        







        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            buscarAsignacion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtperidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperidActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbl_Aaplicacion;
    private javax.swing.JLabel lbl_code;
    private javax.swing.JLabel lbl_code1;
    private javax.swing.JLabel lbl_code2;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaAplicaciones;
    private javax.swing.JTable tablaAsignacion;
    private javax.swing.JTextField txtapid;
    private javax.swing.JTextField txtperid;
    // End of variables declaration//GEN-END:variables
}
