/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;


import java.util.ArrayList;
import seguridad.modelo.daoPerfilApps;
import seguridad.modelo.daoAplicacion;
import seguridad.modelo.daoBitacora;
import seguridad.controlador.clsPerfilAplicaciones;
import seguridad.controlador.clsAplicacion;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import seguridad.controlador.clsPerfil;
import seguridad.modelo.daoPerfil;


/**
 *
 * @author visitante
 */
public class frmMantenimientoPapps extends javax.swing.JInternalFrame {
    
    
  public void estados() {    
        cbox_estado.addItem("seleccione: "); 
      
    } 
    

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Aplicacion");
        
        daoAplicacion aplicacionDAO = new daoAplicacion();
        List<clsAplicacion> aplicaciones = aplicacionDAO.select();
        tablaVendedores.setModel(modelo);
        
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            
             dato[0] = Integer.toString(aplicaciones.get(i).getId_aplicacion());
            dato[1] = aplicaciones.get(i).getNombreAplicacion();
  
            
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
        
    }
    
      
    public void llenado() {
        DefaultTableModel modelo = new DefaultTableModel();
        
                
        daoPerfil perfilDAO = new daoPerfil();
        List<clsPerfil> perfiles = perfilDAO.select();
                      
        String[] dato = new String[3];
        for (int i = 0; i < perfiles.size(); i++) {
                              
            cbox_estado.addItem(perfiles.get(i).getNombrePerfil());
                    
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
        
    }
   
    public void buscarVendedor()
    {
        clsPerfilAplicaciones AConsultar = new clsPerfilAplicaciones();
        daoPerfilApps perDAO = new daoPerfilApps();
        AConsultar.setPerid(Jnombre.getText());
        DefaultTableModel modelo = new DefaultTableModel();
            
        modelo.addColumn("PerfilID");
        modelo.addColumn("AplicacionID");
        modelo.addColumn("NombreAPL");
        
        //daoPerfilApps aplicacion = new daoPerfilApps();
        List<clsPerfilAplicaciones> aplicaciones = perDAO.select2(AConsultar);
        tablaAsignacion.setModel(modelo);
                
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            dato[0] = aplicaciones.get(i).getAplid();
            dato[1] = aplicaciones.get(i).getPerid();
            dato[2] = aplicaciones.get(i).getAplnombre();
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    
    }
           
           

    

   

    public frmMantenimientoPapps() {
        initComponents();
        llenadoDeTablas();
        llenado();
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        lbl_Aaplicacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jnombre = new javax.swing.JTextField();
        lbl_code1 = new javax.swing.JLabel();
        cbox_estado = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsignacion = new javax.swing.JTable();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Perfil aplicaciones");
        setPreferredSize(new java.awt.Dimension(900, 400));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Aaplicacion.setText("Aplicaciones  Asignacion");
        getContentPane().add(lbl_Aaplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel2.setText("Aplicaciones  Disponibles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        Jnombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jnombre.setEnabled(false);
        Jnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnombreActionPerformed(evt);
            }
        });
        getContentPane().add(Jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 220, -1));

        lbl_code1.setText("PERFIILES:");
        getContentPane().add(lbl_code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, -1));

        cbox_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbox_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_estadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbox_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 34, 160, 20));

        jButton4.setText("<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, -1));

        jButton5.setText(">");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, -1));

        jButton6.setText("<<");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 50, -1));

        jButton7.setText(">>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 50, -1));

        jLabel1.setText("Asignar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 50, -1));

        jLabel3.setText("Quitar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 50, -1));

        jLabel4.setText("Editar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 204, 255));
        jButton8.setText("Grabar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 80, -1));

        jRadioButton1.setText("Perfiles");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jRadioButton2.setText("Aplicaciones");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jButton9.setText("Limpiar");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 210));

        tablaAsignacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aplicacion"
            }
        ));
        jScrollPane2.setViewportView(tablaAsignacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 360, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JnombreActionPerformed

    private void cbox_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_estadoActionPerformed
        // TODO add your handling code here:
         Jnombre.setText(cbox_estado.getSelectedItem().toString());
    }//GEN-LAST:event_cbox_estadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TableModel modelo1= tablaVendedores.getModel();
        int[]filas=tablaVendedores.getSelectedRows();
       
        Object[]row=new Object[2];
  
        DefaultTableModel modelo2= (DefaultTableModel)tablaAsignacion.getModel();
        DefaultTableModel modelo3= (DefaultTableModel)tablaVendedores.getModel();
        for(int i=0; i<filas.length; i++){
            row[0]=modelo1.getValueAt(filas[i], 0);
            row[1]=modelo1.getValueAt(filas[i], 1);
        }
            
            modelo2.addRow(row);
            modelo3.removeRow(tablaVendedores.getSelectedRow());
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        daoBitacora Bitacora= new daoBitacora();
        frmDerecho venatana = new frmDerecho();
        
        venatana.txtusuario.setText(Jnombre.getText());
        venatana.txtfecha.setText(Bitacora.fechaActual());
        venatana.txtapli.setText(title);
        venatana.show();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        TableModel modelo1= tablaVendedores.getModel();
        int[]filas=tablaVendedores.getSelectedRows();
       
        Object[]row=new Object[2];
  
        DefaultTableModel modelo2= (DefaultTableModel)tablaAsignacion.getModel();
        DefaultTableModel modelo3= (DefaultTableModel)tablaVendedores.getModel();
        for(int i=0; i<filas.length; i++){
            row[0]=modelo1.getValueAt(filas[i], 0);
            row[1]=modelo1.getValueAt(filas[i], 1);
        }
            
            modelo2.addRow(row);
            modelo3.removeRow(tablaVendedores.getSelectedRow());
                                   
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TableModel modelo1= tablaAsignacion.getModel();
        int[]filas=tablaAsignacion.getSelectedRows();
        Object[]row=new Object[2];
  
        DefaultTableModel modelo2= (DefaultTableModel)tablaVendedores.getModel();
        DefaultTableModel modelo3= (DefaultTableModel)tablaAsignacion.getModel();
        for(int i=0; i<filas.length; i++){
            row[0]=modelo1.getValueAt(filas[i], 0);
            row[1]=modelo1.getValueAt(filas[i], 1);
        }
         modelo2.addRow(row);
            modelo3.removeRow(tablaAsignacion.getSelectedRow());
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jnombre;
    private javax.swing.JComboBox<String> cbox_estado;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbl_Aaplicacion;
    private javax.swing.JLabel lbl_code1;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaAsignacion;
    private javax.swing.JTable tablaVendedores;
    // End of variables declaration//GEN-END:variables
}
