/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridad.vista;


import seguridad.modelo.daoPerfilApps;
import seguridad.modelo.daoAplicacion;
import seguridad.controlador.clsPerfilAplicaciones;
import seguridad.controlador.clsAplicacion;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import seguridad.controlador.clsPerfil;
import seguridad.modelo.daoPerfil;


/**
 *
 * @author visitante
 */
public class frmMantenimientoPapps extends javax.swing.JInternalFrame {
    


    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("ID");
        modelo.addColumn("Aplicacion");
        
        daoAplicacion aplicacionDAO = new daoAplicacion();
        List<clsAplicacion> aplicaciones = aplicacionDAO.select();
        tablaVendedores.setModel(modelo);
        
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            
             dato[0] = Integer.toString(aplicaciones.get(i).getId_aplicacion());
            dato[1] = aplicaciones.get(i).getNombreAplicacion();
        
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
        
    }
      
   
    public void buscarVendedor()
    {
        clsPerfilAplicaciones AConsultar = new clsPerfilAplicaciones();
        daoPerfilApps perDAO = new daoPerfilApps();
        AConsultar.setPerid(txtperid.getText());
        DefaultTableModel modelo = new DefaultTableModel();
            
        modelo.addColumn("PerfilID");
        modelo.addColumn("AplicacionID");
        modelo.addColumn("NombreAPL");
        
        //daoPerfilApps aplicacion = new daoPerfilApps();
        List<clsPerfilAplicaciones> aplicaciones = perDAO.select2(AConsultar);
        tablaAsignacion.setModel(modelo);
                
        String[] dato = new String[3];
        for (int i = 0; i < aplicaciones.size(); i++) {
            dato[0] = aplicaciones.get(i).getAplid();
            dato[1] = aplicaciones.get(i).getPerid();
            dato[2] = aplicaciones.get(i).getAplnombre();
           
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    
    }
           
           

    

   

    public frmMantenimientoPapps() {
        initComponents();
        llenadoDeTablas(); 
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb2 = new javax.swing.JLabel();
        lbusu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAsignacion = new javax.swing.JTable();
        lbl_Aaplicacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_code = new javax.swing.JLabel();
        txtapid = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtperid = new javax.swing.JTextField();
        lbl_code1 = new javax.swing.JLabel();

        lb2.setForeground(new java.awt.Color(204, 204, 204));
        lb2.setText(".");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Perfil aplicaciones");
        setPreferredSize(new java.awt.Dimension(900, 400));
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAsignacion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aplicacion"
            }
        ));
        jScrollPane2.setViewportView(tablaAsignacion);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 300, 210));

        lbl_Aaplicacion.setText("Asignacion de Aplicaciones");
        getContentPane().add(lbl_Aaplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel2.setText("Aplicaciones ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        lbl_code.setText("Codigo de la App A insertar");
        getContentPane().add(lbl_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 150, -1));

        txtapid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapidActionPerformed(evt);
            }
        });
        getContentPane().add(txtapid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 100, -1));

        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 290, 210));

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 140, 80, -1));

        jButton3.setText("Eliminar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 180, 80, -1));

        jButton4.setText("Agregar todos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 220, 80, -1));

        jButton5.setText("Eliminar todos");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 260, 80, -1));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        txtperid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtperidActionPerformed(evt);
            }
        });
        getContentPane().add(txtperid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 100, -1));

        lbl_code1.setText("CODIGO PERFIIL:");
        getContentPane().add(lbl_code1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                               
           daoPerfilApps vendedorDAO = new daoPerfilApps();
        clsPerfilAplicaciones vendedorAInsertar = new clsPerfilAplicaciones();
        vendedorAInsertar.setPerid(txtperid.getText());
         vendedorAInsertar.setAplid(txtapid.getText());
        vendedorDAO.insert(vendedorAInsertar);
        llenadoDeTablas();
   
        







        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            buscarVendedor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtperidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtperidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtperidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbl_Aaplicacion;
    private javax.swing.JLabel lbl_code;
    private javax.swing.JLabel lbl_code1;
    private javax.swing.JLabel lbusu;
    private javax.swing.JTable tablaAsignacion;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtapid;
    private javax.swing.JTextField txtperid;
    // End of variables declaration//GEN-END:variables
}
